### ISSUE TITLE
ImportError introduced with 898805560e9d98dca476d784891cd4b4a7c3852a

### ISSUE THREAD

**Issue by errrrata** [shpi/zero_main_application#5]
Hi,

When jumping to 898805560e9d98dca476d784891cd4b4a7c3852a (coming from d3edf6b304605cb8ec056a850b8d49c14451031b - latest SHPI.zero desktop image), I am getting the following error:

```
WARNING:root:Hint: No SHT found
WARNING:root:Hint: AHT10 calibrated
WARNING:root:Hint: No BH1750
glGetError 0x500
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import shpi.main
  File "/home/pi/zero_main_application/shpi/main.py", line 219, in <module>
    slides.append(importlib.import_module("shpi.slides." + slidestring))
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/pi/zero_main_application/shpi/slides/weather.py", line 273, in <module>
    init()
  File "/home/pi/zero_main_application/shpi/slides/weather.py", line 50, in init
    from pyowm.commons.enums import SubscriptionTypeEnum
ImportError: cannot import name 'SubscriptionTypeEnum' from 'pyowm.commons.enums' (/usr/local/lib/python3.7/dist-packages/pyowm/commons/enums.py)
q^CException ignored in: <module 'threading' from '/usr/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 1281, in _shutdown
    t.join()
  File "/usr/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
```

I have eventually solved it by upgrading pip3 
`sudo -H pip3 install --upgrade pip`
and upgrading `pyowm`

`sudo -H pip3 install --upgrade pyowm`

You may want to add a note for this

**Comment by shpi** [comment]
Thanks.
